# Generated by Django 5.2.10 on 2026-02-02 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Scheduler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plant', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=50)),
                ('instrument', models.CharField(blank=True, max_length=50, null=True)),
                ('module', models.CharField(max_length=100)),
                ('process', models.CharField(max_length=100)),
                ('interval', models.IntegerField(blank=True, null=True)),
                ('uom', models.CharField(blank=True, max_length=20, null=True)),
                ('frequency', models.CharField(blank=True, max_length=20, null=True)),
                ('username', models.CharField(blank=True, max_length=50, null=True)),
                ('table_name', models.CharField(blank=True, max_length=50, null=True)),
                ('status', models.CharField(default='Active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
