# Generated by Django 5.2.10 on 2026-02-02 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scheduler',
            old_name='frequency',
            new_name='interval_units',
        ),
        migrations.RemoveField(
            model_name='scheduler',
            name='uom',
        ),
        migrations.AddField(
            model_name='scheduler',
            name='business_unit',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='scheduler',
            name='database',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='scheduler',
            name='effected_from',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scheduler',
            name='execution_frequency',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='scheduler',
            name='host_ip',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scheduler',
            name='password',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='scheduler',
            name='port',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scheduler',
            name='target_dir',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
