# Generated by Django 5.2.10 on 2026-02-02 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0002_rename_frequency_scheduler_interval_units_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scheduler',
            old_name='interval_units',
            new_name='frequency',
        ),
        migrations.RemoveField(
            model_name='scheduler',
            name='business_unit',
        ),
        migrations.RemoveField(
            model_name='scheduler',
            name='database',
        ),
        migrations.RemoveField(
            model_name='scheduler',
            name='effected_from',
        ),
        migrations.RemoveField(
            model_name='scheduler',
            name='execution_frequency',
        ),
        migrations.RemoveField(
            model_name='scheduler',
            name='host_ip',
        ),
        migrations.RemoveField(
            model_name='scheduler',
            name='password',
        ),
        migrations.RemoveField(
            model_name='scheduler',
            name='port',
        ),
        migrations.RemoveField(
            model_name='scheduler',
            name='target_dir',
        ),
        migrations.AddField(
            model_name='scheduler',
            name='uom',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='scheduler',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Active', max_length=10),
        ),
    ]
