# Generated by Django 5.2.10 on 2026-02-02 06:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0003_rename_interval_units_scheduler_frequency_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduler',
            name='business_unit',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='scheduler',
            name='database',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='scheduler',
            name='effected_from',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scheduler',
            name='host_ip_address',
            field=models.CharField(blank=True, max_length=45, null=True, validators=[django.core.validators.RegexValidator(message='Enter a valid IP address (IPv4/IPv6).', regex='^([0-9a-fA-F:.]+)$')]),
        ),
        migrations.AddField(
            model_name='scheduler',
            name='password_secure_key',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='scheduler',
            name='port',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(65535)]),
        ),
        migrations.AddField(
            model_name='scheduler',
            name='target_dir',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='scheduler',
            name='interval',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='scheduler',
            name='uom',
            field=models.CharField(blank=True, help_text='Interval Units (e.g., minutes, hours, days)', max_length=20, null=True),
        ),
    ]
