# Generated by Django 5.2.10 on 2026-02-02 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0004_scheduler_business_unit_scheduler_database_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scheduler',
            name='business_unit',
        ),
        migrations.RemoveField(
            model_name='scheduler',
            name='database',
        ),
        migrations.RemoveField(
            model_name='scheduler',
            name='effected_from',
        ),
        migrations.RemoveField(
            model_name='scheduler',
            name='host_ip_address',
        ),
        migrations.RemoveField(
            model_name='scheduler',
            name='password_secure_key',
        ),
        migrations.RemoveField(
            model_name='scheduler',
            name='port',
        ),
        migrations.RemoveField(
            model_name='scheduler',
            name='target_dir',
        ),
        migrations.AlterField(
            model_name='scheduler',
            name='interval',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='scheduler',
            name='uom',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
