# Generated by Django 5.2.10 on 2026-02-03 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0005_remove_scheduler_business_unit_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scheduler',
            name='frequency',
        ),
        migrations.AddField(
            model_name='scheduler',
            name='business_unit',
            field=models.CharField(choices=[('QA', 'QA'), ('QC', 'QC'), ('R&D', 'R&D')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='scheduler',
            name='execution_frequency',
            field=models.CharField(blank=True, choices=[('Daily', 'Daily'), ('Weekly', 'Weekly'), ('Monthly', 'Monthly')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='scheduler',
            name='instrument',
            field=models.CharField(blank=True, choices=[('HPLC', 'HPLC'), ('GC', 'GC'), ('LCMS', 'LCMS')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='scheduler',
            name='location',
            field=models.CharField(choices=[('India', 'India'), ('USA', 'USA')], max_length=50),
        ),
        migrations.AlterField(
            model_name='scheduler',
            name='module',
            field=models.CharField(choices=[('Scheduler', 'Scheduler'), ('Backup', 'Backup'), ('Sync', 'Sync')], max_length=50),
        ),
        migrations.AlterField(
            model_name='scheduler',
            name='plant',
            field=models.CharField(choices=[('Plant-1', 'Plant-1'), ('Plant-2', 'Plant-2')], max_length=50),
        ),
        migrations.AlterField(
            model_name='scheduler',
            name='process',
            field=models.CharField(choices=[('Application Data Backup', 'Application Data Backup'), ('DB Sync', 'DB Sync'), ('Files Sync', 'Files Sync'), ('Empower Settings', 'Empower Settings'), ('Chromeleon Settings', 'Chromeleon Settings')], max_length=50),
        ),
        migrations.AlterField(
            model_name='scheduler',
            name='uom',
            field=models.CharField(blank=True, choices=[('Minutes', 'Minutes'), ('Hours', 'Hours'), ('Days', 'Days')], max_length=20, null=True),
        ),
    ]
