# Generated by Django 5.2.10 on 2026-02-03 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0006_remove_scheduler_frequency_scheduler_business_unit_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scheduler',
            old_name='uom',
            new_name='interval_units',
        ),
        migrations.AddField(
            model_name='scheduler',
            name='alert_before_days',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scheduler',
            name='client',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='scheduler',
            name='data_vault',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='scheduler',
            name='database',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='scheduler',
            name='effected_from',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scheduler',
            name='empower_data_source',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='scheduler',
            name='empower_default_project',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='scheduler',
            name='empower_password',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='scheduler',
            name='empower_user_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='scheduler',
            name='file_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='scheduler',
            name='group',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='scheduler',
            name='host_ip_address',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='scheduler',
            name='host_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='scheduler',
            name='password_expiring_days',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scheduler',
            name='password_or_secure_key',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='scheduler',
            name='port',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='scheduler',
            name='project_contains',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='scheduler',
            name='resume_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scheduler',
            name='service',
            field=models.CharField(choices=[('START', 'Start'), ('STOP', 'Stop')], default='START', max_length=10),
        ),
        migrations.AddField(
            model_name='scheduler',
            name='skip_project',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='scheduler',
            name='target_dir',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='scheduler',
            name='business_unit',
            field=models.CharField(choices=[('BU1', 'Business Unit 1'), ('BU2', 'Business Unit 2')], max_length=50),
        ),
        migrations.AlterField(
            model_name='scheduler',
            name='execution_frequency',
            field=models.CharField(blank=True, choices=[('Once', 'Once'), ('Daily', 'Daily'), ('Weekly', 'Weekly'), ('Monthly', 'Monthly')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='scheduler',
            name='instrument',
            field=models.CharField(blank=True, choices=[('HPLC', 'HPLC'), ('GC', 'GC')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='scheduler',
            name='location',
            field=models.CharField(choices=[('LOC1', 'Location 1'), ('LOC2', 'Location 2')], max_length=50),
        ),
        migrations.AlterField(
            model_name='scheduler',
            name='module',
            field=models.CharField(choices=[('MOD1', 'Module 1'), ('MOD2', 'Module 2')], max_length=50),
        ),
        migrations.AlterField(
            model_name='scheduler',
            name='plant',
            field=models.CharField(choices=[('PLANT1', 'Plant 1'), ('PLANT2', 'Plant 2')], max_length=50),
        ),
        migrations.AlterField(
            model_name='scheduler',
            name='process',
            field=models.CharField(choices=[('DB_SYNC', 'DB Sync'), ('FILE_SYNC', 'File Sync'), ('EMPOWER', 'Empower')], max_length=50),
        ),
        migrations.AlterField(
            model_name='scheduler',
            name='table_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='scheduler',
            name='username',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
