# Generated by Django 5.2.10 on 2026-02-03 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0007_rename_uom_scheduler_interval_units_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scheduler',
            old_name='interval_units',
            new_name='uom',
        ),
        migrations.RemoveField(
            model_name='scheduler',
            name='alert_before_days',
        ),
        migrations.RemoveField(
            model_name='scheduler',
            name='client',
        ),
        migrations.RemoveField(
            model_name='scheduler',
            name='data_vault',
        ),
        migrations.RemoveField(
            model_name='scheduler',
            name='database',
        ),
        migrations.RemoveField(
            model_name='scheduler',
            name='effected_from',
        ),
        migrations.RemoveField(
            model_name='scheduler',
            name='empower_data_source',
        ),
        migrations.RemoveField(
            model_name='scheduler',
            name='empower_default_project',
        ),
        migrations.RemoveField(
            model_name='scheduler',
            name='empower_password',
        ),
        migrations.RemoveField(
            model_name='scheduler',
            name='empower_user_name',
        ),
        migrations.RemoveField(
            model_name='scheduler',
            name='file_name',
        ),
        migrations.RemoveField(
            model_name='scheduler',
            name='group',
        ),
        migrations.RemoveField(
            model_name='scheduler',
            name='host_ip_address',
        ),
        migrations.RemoveField(
            model_name='scheduler',
            name='host_name',
        ),
        migrations.RemoveField(
            model_name='scheduler',
            name='password_expiring_days',
        ),
        migrations.RemoveField(
            model_name='scheduler',
            name='password_or_secure_key',
        ),
        migrations.RemoveField(
            model_name='scheduler',
            name='port',
        ),
        migrations.RemoveField(
            model_name='scheduler',
            name='project_contains',
        ),
        migrations.RemoveField(
            model_name='scheduler',
            name='resume_date',
        ),
        migrations.RemoveField(
            model_name='scheduler',
            name='service',
        ),
        migrations.RemoveField(
            model_name='scheduler',
            name='skip_project',
        ),
        migrations.RemoveField(
            model_name='scheduler',
            name='target_dir',
        ),
        migrations.AlterField(
            model_name='scheduler',
            name='business_unit',
            field=models.CharField(choices=[('QA', 'QA'), ('QC', 'QC'), ('R&D', 'R&D')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='scheduler',
            name='execution_frequency',
            field=models.CharField(blank=True, choices=[('Daily', 'Daily'), ('Weekly', 'Weekly'), ('Monthly', 'Monthly')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='scheduler',
            name='instrument',
            field=models.CharField(blank=True, choices=[('HPLC', 'HPLC'), ('GC', 'GC'), ('LCMS', 'LCMS')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='scheduler',
            name='location',
            field=models.CharField(choices=[('India', 'India'), ('USA', 'USA')], max_length=50),
        ),
        migrations.AlterField(
            model_name='scheduler',
            name='module',
            field=models.CharField(choices=[('Scheduler', 'Scheduler'), ('Backup', 'Backup'), ('Sync', 'Sync')], max_length=50),
        ),
        migrations.AlterField(
            model_name='scheduler',
            name='plant',
            field=models.CharField(choices=[('Plant-1', 'Plant-1'), ('Plant-2', 'Plant-2')], max_length=50),
        ),
        migrations.AlterField(
            model_name='scheduler',
            name='process',
            field=models.CharField(choices=[('Application Data Backup', 'Application Data Backup'), ('DB Sync', 'DB Sync'), ('Files Sync', 'Files Sync'), ('Empower Settings', 'Empower Settings'), ('Chromeleon Settings', 'Chromeleon Settings')], max_length=50),
        ),
        migrations.AlterField(
            model_name='scheduler',
            name='table_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='scheduler',
            name='username',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
