# Generated by Django 5.2.10 on 2026-02-03 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0008_rename_interval_units_scheduler_uom_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduler',
            name='data_vault',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='scheduler',
            name='database',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='scheduler',
            name='effected_from',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scheduler',
            name='execution_frequency_value',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scheduler',
            name='host_ip',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='scheduler',
            name='password',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='scheduler',
            name='port',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scheduler',
            name='skip_project',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='scheduler',
            name='source_dir',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='scheduler',
            name='target_dir',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='scheduler',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='scheduler',
            name='business_unit',
            field=models.CharField(blank=True, choices=[('QA', 'QA'), ('QC', 'QC'), ('R&D', 'R&D')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='scheduler',
            name='table_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
