# Generated by Django 5.2.10 on 2026-02-04 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0009_scheduler_data_vault_scheduler_database_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduler',
            name='location',
            field=models.CharField(blank=True, choices=[('India', 'India'), ('USA', 'USA')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='scheduler',
            name='module',
            field=models.CharField(blank=True, choices=[('Scheduler', 'Scheduler'), ('Backup', 'Backup'), ('Sync', 'Sync')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='scheduler',
            name='password',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='scheduler',
            name='plant',
            field=models.CharField(blank=True, choices=[('Plant-1', 'Plant-1'), ('Plant-2', 'Plant-2')], max_length=50, null=True),
        ),
    ]
