# Generated by Django 5.2.10 on 2026-02-04 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0010_alter_scheduler_location_alter_scheduler_module_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduler',
            name='chromeleon_alert_days',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scheduler',
            name='chromeleon_group',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='scheduler',
            name='chromeleon_project_contains',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='scheduler',
            name='chromeleon_pwd_days',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scheduler',
            name='chromeleon_service',
            field=models.CharField(blank=True, choices=[('Start', 'Start'), ('Stop', 'Stop')], max_length=10, null=True),
        ),
    ]
