# Generated by Django 5.2.10 on 2026-02-04 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0011_scheduler_chromeleon_alert_days_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scheduler',
            name='chromeleon_alert_days',
        ),
        migrations.RemoveField(
            model_name='scheduler',
            name='chromeleon_group',
        ),
        migrations.RemoveField(
            model_name='scheduler',
            name='chromeleon_project_contains',
        ),
        migrations.RemoveField(
            model_name='scheduler',
            name='chromeleon_pwd_days',
        ),
        migrations.RemoveField(
            model_name='scheduler',
            name='chromeleon_service',
        ),
        migrations.AlterField(
            model_name='scheduler',
            name='location',
            field=models.CharField(choices=[('India', 'India'), ('USA', 'USA')], max_length=50),
        ),
        migrations.AlterField(
            model_name='scheduler',
            name='module',
            field=models.CharField(choices=[('Scheduler', 'Scheduler'), ('Backup', 'Backup'), ('Sync', 'Sync')], max_length=50),
        ),
        migrations.AlterField(
            model_name='scheduler',
            name='password',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='scheduler',
            name='plant',
            field=models.CharField(choices=[('Plant-1', 'Plant-1'), ('Plant-2', 'Plant-2')], max_length=50),
        ),
    ]
