# Generated by Django 5.2.10 on 2026-02-05 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0013_scheduler_empower_client_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduler',
            name='chromeleon_alert_days',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scheduler',
            name='chromeleon_group',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='scheduler',
            name='chromeleon_host',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='scheduler',
            name='chromeleon_location',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='scheduler',
            name='chromeleon_module',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='scheduler',
            name='chromeleon_password',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='scheduler',
            name='chromeleon_plant',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='scheduler',
            name='chromeleon_process',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='scheduler',
            name='chromeleon_project_contains',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='scheduler',
            name='chromeleon_pwd_days',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scheduler',
            name='chromeleon_resume_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scheduler',
            name='chromeleon_service',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='scheduler',
            name='chromeleon_status',
            field=models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Active', max_length=10),
        ),
        migrations.AddField(
            model_name='scheduler',
            name='chromeleon_username',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
