# Generated by Django 5.2.10 on 2026-02-05 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0014_scheduler_chromeleon_alert_days_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scheduler',
            old_name='data_vault',
            new_name='chromeleon_data_vault',
        ),
        migrations.RenameField(
            model_name='scheduler',
            old_name='skip_project',
            new_name='chromeleon_skip_project',
        ),
    ]
