# Generated by Django 5.2.10 on 2026-02-05 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0015_rename_data_vault_scheduler_chromeleon_data_vault_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scheduler',
            name='execution_frequency_value',
        ),
    ]
